name: vscode_for_android
description: VS Code for Android
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.4+16
code_server: 4.96.2
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  signale: ^0.0.9
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  url_launcher: ^6.1.10
  retrofit: 
  archive: 
  dio: 
  cupertino_icons: ^1.0.2
  get: 
  permission_handler: ^10.2.0
  flutter_markdown: ^0.7.4+3
  xterm:
    git:
      url: https://github.com/TerminalStudio/xterm.dart
      ref: master
  settings:
    git: https://github.com/nightmare-space/settings
  flutter_pty:
    git: https://github.com/TerminalStudio/flutter_pty
  global_repository:
    git: https://github.com/edeegg/global_repository
  path: ^1.8.0
  device_info_plus: 8.1.0
  meta: ^1.11.0
  typed_data: ^1.3.2
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  
  
